# Exception Definition

[Sinemarc Api](../index.md#sinemarc-api) /
Exception Definition


- [Exception Definition](#exception-definition)
  - [src_missing_rights](#src_missing_rights)
  - [src_missing_token](#src_missing_token)
  - [src_missing_value](#src_missing_value)
  - [src_wrong_datatype](#src_wrong_datatype)
  - [src_wrong_usage](#src_wrong_usage)

## src_missing_rights
There is not enoug right given to the api user
[Show source in exception_definition.py:26](../../../sinemarc_api/lib/exception_definition.py#L26)





## src_missing_token
There is no token given, normally tokens are handled directly by the libary. Please check, whether you use the functions of the pi
[Show source in exception_definition.py:24](../../../sinemarc_api/lib/exception_definition.py#L24)





## src_missing_value
Not all mandatory values given for this function
[Show source in exception_definition.py:30](../../../sinemarc_api/lib/exception_definition.py#L30)




## src_wrong_datatype
Wrong datatype given
[Show source in exception_definition.py:28](../../../sinemarc_api/lib/exception_definition.py#L28)



## src_wrong_usage
This is only raised if the function is wrongly used
[Show source in exception_definition.py:32](../../../sinemarc_api/lib/exception_definition.py#L32)

